//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPuja.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long bookingID { get; set; }
        public Nullable<long> ordersID { get; set; }
        public Nullable<long> menuID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
    }
}
