//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPuja.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryBoy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryBoy()
        {
            this.Contacts = new HashSet<Contact>();
            this.DeliveryBoyFeedbacks = new HashSet<DeliveryBoyFeedback>();
            this.Orders = new HashSet<Order>();
        }
    
        public long deliveryBoyID { get; set; }
        public string deliveryBoyName { get; set; }
        public string deliveryBoyEmail { get; set; }
        public Nullable<long> addressID { get; set; }
        public string deliveryBoyUsername { get; set; }
        public string deliveryBoyPassword { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> deliveryBoyAvailability { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryBoyFeedback> DeliveryBoyFeedbacks { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
