//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPuja.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryBoyFeedback
    {
        public long feedbackID { get; set; }
        public Nullable<long> deliveryBoyID { get; set; }
        public Nullable<long> customerID { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public Nullable<long> ordersID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryBoy DeliveryBoy { get; set; }
        public virtual Order Order { get; set; }
    }
}
