//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetPuja.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiffinProvider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiffinProvider()
        {
            this.Contacts = new HashSet<Contact>();
            this.Menus = new HashSet<Menu>();
            this.Orders = new HashSet<Order>();
            this.TiffinFeedbacks = new HashSet<TiffinFeedback>();
        }
    
        public long tiffinProviderID { get; set; }
        public string tiffinProviderName { get; set; }
        public string tiffinProviderEmail { get; set; }
        public string restaurantName { get; set; }
        public Nullable<long> addressID { get; set; }
        public string tiffinProviderUsername { get; set; }
        public string tiffinProviderPassword { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> roleID { get; set; }
        public string tiffinProviderImage { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiffinFeedback> TiffinFeedbacks { get; set; }
    }
}
